version: '2'
services:
  demo:
    image: odoo:10.0
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    #environment:
    #  - TERM=xterm-256color
    #stdin_open: true
    tty: true
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      #- TERM=xterm-256color
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  odoo-web-data:
  odoo-db-data: